#!/usr/bin/env bash

AZURE_COSMOS_DB_ACCOUNT_NAME="$AZURE_COSMOS_DB_ACCOUNT_NAME"

AZURE_COSMOS_DB_ACCOUNT_KEY="$AZURE_COSMOS_DB_ACCOUNT_KEY"

echo AZURE_COSMOS_DB_ACCOUNT_NAME

echo AZURE_COSMOS_DB_ACCOUNT_KEY